version: '3'

services:
  nginx:
    image: nginx:alpine
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/log/nginx
      - /var/run
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

  app:
    image: keymetrics/pm2-docker-alpine:latest
    volumes:
      - ./app:/app
    environment:
      - DEBUG="*" 
    command:
      pm2-docker start process.yml
    
